### ISSUE TITLE
Icon not visible in Yosemite's "dark menu bar"

### ISSUE THREAD

**Issue by sgabler** [tomighty/tomighty#106] opened 2014-10-21 14:43 UTC
![screen shot 2014-10-21 at 16 38 28](https://cloud.githubusercontent.com/assets/3625477/4720324/40f55bfe-5930-11e4-9834-8cf1a015ca53.png)

Yosemite has introduced the "dark menu bar and Dock", which leads to the tomighty icon no longer being visible. Only if you click on the area where you think it might be, it's visible (see screenshot).

Can we modify the existing icon, or put another one based on the OS's settings?

**Comment by sgrosse** [comment] 2015-03-19 08:23
+1

**Comment by pperez** [comment] 2015-04-13 22:24
+1 :+1:

**Comment by andreyz** [comment] 2015-05-19 13:39
:+1:

**Comment by sgrosse** [comment] 2015-07-13 09:24
+1

**Comment by m9n** [comment] 2015-10-20 09:41
Workaround - if anyone else needs this:
1. If you haven't already, quit Tomighty (don't know if this is necessary, but I didn't want to modify the contents of the app with it still running).
2. Open a Finder window and go to Applications > Tomighty(.app), secondary-click and choose "Show package contents"
3. Inside the Tomighty.app package, navigate to Contents > Resources.
4. Back up the file 'status-normal.tiff' by renaming it something like '__status-normal.tiff'
5. Copy status-white.tiff and call it status-normal.tiff.
6. Start up Tomighty again and ta-da!

Next up, I might see if I can edit all the icons to recreate them for my retina display :)

**Comment by carlosjgp** [comment] 2015-10-24 06:42
:+1:

_m9n_, nice approach!

**Comment by Sgoettschkes** [comment] 2015-12-14 10:41
@m9n This works great, thank you.

**Comment by dody87** [comment] 2016-01-26 14:02
it works. Thanks @m9n.

**Comment by luebken** [comment] 2016-02-09 13:53
@m9n thanks. works.

**Comment by keikoro** [comment] 2016-04-05 11:09
+1 and thanks for the workaround, @m9n!

**Comment by ogzA** [comment] 2016-06-24 15:39
it worked, thank you very much!, @m9n

**Comment by dvntucker** [comment] 2016-09-04 21:03
Closing this as a duplicate of:

https://github.com/tomighty/tomighty-osx/issues/21

The fix for this is due in 1.1.

**Closed as completed by dvntucker** 2016-09-04 21:03 UTC
